# Generated by Django 2.1 on 2021-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210630_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
